# Travis configuration file
# http://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "2.7"

# Installing Dependencies...
install:
  - sudo apt-get update
  - sudo apt-get install libusb-dev saods9 xpa-tools sextractor
  - pip install -r requirements.txt
  - pip install coverage coveralls  # Needed to nosetests coverage
  - python setup.py install

# Installing chimera...
script:
  - nosetests

